services:
  - name: documind
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    preDeployCommand: alembic upgrade head
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_ENV
        value: production
